apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: services-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "192.168.64.14" #Minikube ip
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-services-a
spec:
  hosts:
  - "192.168.64.14" 
  gateways:
  - services-gateway
  http:
  - match:
    - uri:
        prefix: /home
    route: 
    - destination:
        host: servicea.default.svc.cluster.local

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-services-b
spec:
  hosts:
  - "192.168.64.14" 
  gateways:
  - services-gateway
  http:
  - match:
    - uri:
        prefix: /weatherforecast
    route: 
    - destination:
        host: serviceb.default.svc.cluster.local